/* The Little Prince film (illustrated version) — extra pictures made for the film, between the book's pictures, so that
   no picture stays on screen much longer than a minute and a half. Each one appears from the line containing `at`
   (a phrase of that chapter; node tools/test.js checks it is found exactly once) until the next picture.
   Files: ../images/film/<id>.jpg (1200x900), drawn with Codex from the chapter plates' style and characters
   (images/README.md). Their character positions for the camera are in shots.js.
   Listed in story order; the numbers in the ids are not (10-f6 … were added later between 10-f3 and 10-f4). */
window.LP_FILM_FRAMES = [
  { id: '01-f1', ch: 1, at: "So I had to choose another job",
    alt: "the narrator as a young pilot flying a small plane over the world" },
  { id: '01-f2', ch: 1, at: "Whenever I met one who seemed",
    alt: "the pilot showing his drawing number 1 to a grown-up, who sees only a hat" },
  { id: '02-f1', ch: 2, at: "So on the first night I fell asleep on the sand",
    alt: "the pilot asleep on the sand beside his plane, alone in the desert under the stars" },
  { id: '02-f2', ch: 2, at: "I jumped to my feet as if",
    alt: "at daybreak the pilot jumps up, astonished, and sees the little prince" },
  { id: '02-f3', ch: 2, at: "When a mystery is too overwhelming",
    alt: "the pilot takes paper and a fountain pen out of his pocket" },
  { id: '03-f1', ch: 3, at: "And the little prince burst into a very pretty peal of laughter",
    alt: "the little prince laughs at the idea that the pilot fell from the sky" },
  { id: '03-f2', ch: 3, at: "taking my sheep out of his pocket",
    alt: "the little prince gazes at the drawing of the box with the sheep inside" },
  { id: '04-f1', ch: 4, at: "But nobody believed him because of the clothes he wore",
    alt: "the Turkish astronomer presents his discovery in traditional dress and nobody believes him" },
  { id: '04-f2', ch: 4, at: "The astronomer gave his presentation again in 1920",
    alt: "in 1920 the astronomer, now in an elegant suit, is applauded" },
  { id: '04-f3', ch: 4, at: "I saw a beautiful house made of pink bricks",
    alt: "a house of pink bricks, with geraniums in the windows and doves on the roof" },
  { id: '04-f4', ch: 4, at: "So that is one more reason why I bought a box of paints",
    alt: "years later, the pilot at his table with a box of paints, trying to draw the little prince" },
  { id: '05-f1', ch: 5, at: "It's true, isn't it, that sheep eat bushes?",
    alt: "the little prince asks the pilot whether sheep eat bushes" },
  { id: '05-f2', ch: 5, at: "The idea of the herd of elephants made the little prince laugh",
    alt: "elephants piled one on top of the other on a tiny planet" },
  { id: '05-f3', ch: 5, at: "Then it stretches, and at first it shyly pushes",
    alt: "seeds sleeping in the ground, one pushing a little sprout toward the sun" },
  { id: '05-f4', ch: 5, at: "It's a question of discipline",
    alt: "in the morning the little prince pulls up baobab sprouts on his planet" },
  { id: '06-f1', ch: 6, at: "all you had to do was move your chair a few steps",
    alt: "on his tiny planet the little prince moves his chair a few steps to watch the sunset again" },
  { id: '07-f1', ch: 7, at: "At that moment I was very busy trying to unscrew a bolt",
    alt: "the pilot struggles with a stuck bolt while the little prince asks what thorns are for" },
  { id: '07-f2', ch: 7, at: "He saw me there, hammer in hand",
    alt: "the little prince, angry, faces the pilot with his hammer and greasy fingers" },
  { id: '07-f3', ch: 7, at: "I know a planet where there is a gentleman with a bright red face",
    alt: "on a planet, a red-faced gentleman who does nothing but add up numbers" },
  { id: '07-f4', ch: 7, at: "All at once he burst into sobs",
    alt: "at nightfall the pilot takes the sobbing little prince in his arms" },
  { id: '08-f1', ch: 8, at: "decorated with a single ring of petals",
    alt: "simple little flowers with a single ring of petals on the little prince's planet" },
  { id: '08-f2', ch: 8, at: "The little prince, who watched an enormous bud take shape",
    alt: "the little prince watches an enormous bud take shape" },
  { id: '08-f3', ch: 8, at: "Let them come, the tigers, with their claws!",
    alt: "the proud rose shows her four thorns" },
  { id: '08-f4', ch: 8, at: "In the evening you will put me under a glass globe",
    alt: "in the evening the little prince puts the rose under her glass globe" },
  { id: '09-f1', ch: 9, at: "he said to the flower",
    alt: "the little prince says goodbye to his flower" },
  { id: '09-f2', ch: 9, at: "For she did not want him to see her cry",
    alt: "the rose alone on the planet as the little prince leaves with the birds" },
  { id: '10-f1', ch: 10, at: "It is against the rules of the court to yawn",
    alt: "the little prince yawns in front of the king" },
  { id: '10-f2', ch: 10, at: "grandly pulled back a fold of his ermine robe",
    alt: "the king pulls back a fold of his robe so the little prince can sit" },
  { id: '10-f3', ch: 10, at: "With a small, modest gesture the king pointed",
    alt: "the king points to his planet, the other planets and the stars: he rules over everything" },
  { id: '10-f6', ch: 10, at: "Order the sun to set",
    alt: "the little prince asks the king to order the sun to set" },
  { id: '10-f7', ch: 10, at: "who first looked in a big calendar",
    alt: "the king looks in a big calendar before answering" },
  { id: '10-f8', ch: 10, at: "Then you shall judge yourself",
    alt: "the king tells the little prince to judge himself" },
  { id: '10-f4', ch: 10, at: "I rather think there is an old rat somewhere on my planet",
    alt: "an old rat on the king's planet at night" },
  { id: '10-f5', ch: 10, at: "I make you my ambassador!",
    alt: "the little prince leaves; the king calls out that he makes him his ambassador" },
  { id: '13-f1', ch: 13, at: "Little golden things that make lazy people daydream",
    alt: "the businessman at his desk under the stars he counts as his own" },
  { id: '13-f4', ch: 13, at: "I count them and count them again",
    alt: "the businessman counts his stars again and again" },
  { id: '13-f2', ch: 13, at: "And then I lock that paper in a drawer",
    alt: "the businessman locks the paper with the number of his stars in a drawer" },
  { id: '13-f3', ch: 13, at: "and I water her every day",
    alt: "the little prince tells the businessman that he waters his flower and sweeps his volcanoes" },
  { id: '14-f1', ch: 14, at: "So now that it turns all the way around once a minute",
    alt: "the lamplighter's planet turns once a minute: day and night one after the other" },
  { id: '14-f3', ch: 14, at: "I know a way you could rest whenever you want",
    alt: "the little prince shows how to walk slowly and stay in the sun" },
  { id: '14-f2', ch: 14, at: "That man is the only one I could have made my friend",
    alt: "the little prince travels on, looking back at the lamplighter's planet" },
  { id: '15-f4', ch: 15, at: "he has to bring back big stones from it",
    alt: "an explorer must bring back big stones as proof" },
  { id: '15-f1', ch: 15, at: "And the geographer opened his big register",
    alt: "the geographer opens his big register and sharpens his pencil to write down the prince's planet" },
  { id: '15-f2', ch: 15, at: "My flower is ephemeral",
    alt: "the little prince thinks of his flower left alone at home, with only four thorns" },
  { id: '15-f3', ch: 15, at: "The planet Earth,",
    alt: "the geographer advises the planet Earth" },
  { id: '16-f1', ch: 16, at: "First came the turn of the lamplighters of New Zealand",
    alt: "the ballet of the lamplighters lighting their lamps continent after continent" },
  { id: '17-f1', ch: 17, at: "He wound himself around the little prince",
    alt: "the snake winds itself around the little prince's ankle like a gold bracelet" },
  { id: '21-f7', ch: 21, at: "I hunt chickens; people hunt me",
    alt: "the fox says he hunts chickens and people hunt him" },
  { id: '21-f1', ch: 21, at: "Do you see the wheat fields over there?",
    alt: "the fox shows the little prince the golden wheat fields" },
  { id: '21-f2', ch: 21, at: "First you will sit down a little way from me",
    alt: "the little prince sits in the grass a little way from the fox" },
  { id: '21-f3', ch: 21, at: "If you come, for example, at four o'clock",
    alt: "the fox waits, happier and happier, for the little prince to come at four" },
  { id: '21-f4', ch: 21, at: "I am going to cry",
    alt: "the time for leaving: the fox is sad" },
  { id: '21-f5', ch: 21, at: "You are not at all like my rose",
    alt: "the little prince speaks to the roses in the garden" },
  { id: '21-f6', ch: 21, at: "Here is my secret",
    alt: "the fox tells the little prince his secret" },
  { id: '24-f1', ch: 24, at: "I am thirsty too",
    alt: "the pilot and the little prince set off across the desert to look for a well" },
  { id: '24-f2', ch: 24, at: "He was tired. He sat down",
    alt: "the two friends sit on a dune under the stars" },
  { id: '24-f3', ch: 24, at: "I took him in my arms and set off again",
    alt: "the pilot carries the sleeping little prince in the moonlight" },
  { id: '25-f1', ch: 25, at: "He laughed, touched the rope and set the pulley turning",
    alt: "the little prince sets the pulley of the well turning" },
  { id: '25-f2', ch: 25, at: "I lifted the bucket to his lips",
    alt: "the little prince drinks from the bucket with his eyes closed" },
  { id: '25-f3', ch: 25, at: "I took my rough sketches out of my pocket",
    alt: "the little prince laughs at the pilot's drawings" },
  { id: '25-f4', ch: 25, at: "So I sketched a muzzle in pencil",
    alt: "the pilot gives the little prince the drawing of the muzzle, his heart aching" },
  { id: '26-f1', ch: 26, at: "Then I looked down myself at the foot of the wall",
    alt: "a yellow snake raised toward the little prince on the wall; the pilot runs" },
  { id: '26-f2', ch: 26, at: "I reached the wall just in time",
    alt: "the pilot catches the pale little prince in his arms" },
  { id: '26-f7', ch: 26, at: "I have your sheep. And I have the box",
    alt: "in the pilot's arms, the little prince looks far away: he has the sheep, the box and the muzzle" },
  { id: '26-f3', ch: 26, at: "At night you'll look up at the stars",
    alt: "the little prince and the pilot look at the stars together" },
  { id: '26-f8', ch: 26, at: "People have stars, but they aren't the same stars",
    alt: "the stars mean different things to different people" },
  { id: '26-f4', ch: 26, at: "heaps of little bells that know how to laugh",
    alt: "stars like little bells that know how to laugh" },
  { id: '26-f5', ch: 26, at: "That night I did not see him set off",
    alt: "in the night the little prince walks away with quick, determined steps; the pilot catches up" },
  { id: '26-f6', ch: 26, at: "It's here. Let me take one step by myself",
    alt: "the little prince sits down on the sand, afraid; the pilot beside him" },
  { id: '27-f1', ch: 27, at: "The muzzle I drew for the little prince",
    alt: "six years later the pilot looks at his drawing of the muzzle: he forgot the strap" },
  { id: '27-f2', ch: 27, at: "Look at the sky. Ask yourselves",
    alt: "on a tiny planet among the stars, a sheep beside a rose under her glass globe" }
];
