#!/usr/bin/env python3
"""Embed each book's text/*.txt as text/book.js so the game can load it without a server (file:// too).
Run: python3 tools/embed-text.py            (all books under books/)
     python3 tools/embed-text.py books/<id> (one book)
start.sh runs this automatically."""
import glob, json, os, sys
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
dirs = [os.path.join(root, sys.argv[1])] if len(sys.argv) > 1 else sorted(
    d for d in glob.glob(os.path.join(root, 'books', '*')) if os.path.isdir(d) and not os.path.basename(d).startswith('_'))
for d in dirs:
    tdir = os.path.join(d, 'text')
    out = os.path.join(tdir, 'book.js')
    files = sorted(glob.glob(os.path.join(tdir, '*.txt')))
    name = os.path.relpath(d, root)
    if not files:
        if os.path.exists(out):
            os.remove(out)
        print(f'{name}: no text/*.txt (text/book.js removed)' if os.path.exists(tdir) else f'{name}: no text folder')
        continue
    def read(path):
        with open(path, encoding='utf-8', errors='replace') as f:
            return f.read()
    if len(files) == 1:
        src_name, text = os.path.basename(files[0]), read(files[0])
        note = ''
    else:
        # Several files (e.g. one tale per file, named 01-….txt, 02-….txt): join them in name order,
        # one chapter per file, separated by the parser's === delimiter.
        parts = ['===\n' + read(f).strip() + '\n' for f in files]
        src_name, text = f'{len(files)} files ({os.path.basename(files[0])} …)', '\n'.join(parts)
        note = f' — {len(files)} files joined in name order, one chapter each'
    with open(out, 'w', encoding='utf-8') as f:
        f.write('/* generated by tools/embed-text.py — do not edit, do not distribute */\n')
        f.write('window.LP_BOOK = ' + json.dumps({'file': src_name, 'text': text}, ensure_ascii=False) + ';\n')
    print(f'{name}: embedded {src_name} ({len(text):,} chars) into text/book.js{note}')
