#!/usr/bin/env python3
"""Mouth curves and word times for the recorded voices of The Little Prince film (books/little-prince/film/).

For every recording in film/audio/ (listed in film/audio.js by tools/film-voices.py) this writes one entry of
film/timing.js, keyed like the recording:
  mouth  loudness every 50 ms as one digit 0-9 (normalised to the loudest moment of the line); the film opens the
         speaker's mouth by it (motion.js)
  words  [start ms, end ms] for each word of the line, in the order of words() below, from faster-whisper word
         timestamps matched to the script; empty when they could not be matched (then only the subtitle word
         highlight is missing)
The curves come from the final MP3 (after trimming and loudness), so they line up with what the film plays.
Only recordings missing from timing.js are processed; entries for recordings that are gone are dropped.

Run:   uv run --with faster-whisper --with numpy python3 tools/film-timing.py [--chapter N] [--mouth-only]
       (--mouth-only skips whisper: quick, and leaves words empty for new lines)
Needs: node, ffmpeg.
"""
import importlib.util, json, os, re, subprocess, sys, time
from difflib import SequenceMatcher

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FILM = os.path.join(ROOT, 'books', 'little-prince', 'film')
AUDIO = os.path.join(FILM, 'audio')
OUT = os.path.join(FILM, 'timing.js')
RATE, WIN = 16000, 0.05   # whisper takes 16 kHz samples

# the film's word splitting (motion.js WORD): runs of letters/digits, with inner apostrophes ("don't", "it's")
WORD = re.compile(r"[^\W_]+(?:['’][^\W_]+)*")
def words(text):
    return WORD.findall(text)

def norm(w):
    return re.sub(r"[^a-z0-9]", '', w.lower().replace('’', "'"))

def pcm(path):
    raw = subprocess.run(['ffmpeg', '-nostdin', '-loglevel', 'error', '-i', path, '-f', 's16le', '-ac', '1', '-ar', str(RATE), '-'],
                         capture_output=True, check=True).stdout
    return np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768

def mouth(samples):
    """RMS in 50 ms windows, normalised to the line's loudest window, as digits 0-9."""
    n = int(RATE * WIN)
    frames = len(samples) // n + (1 if len(samples) % n else 0)
    if not frames: return ''
    padded = np.zeros(frames * n, dtype=np.float32); padded[:len(samples)] = samples
    rms = np.sqrt((padded.reshape(frames, n) ** 2).mean(axis=1))
    top = np.percentile(rms, 98) or 1
    # a gentle curve so ordinary speech reaches the half-open and open shapes, not only the loudest vowels
    level = np.clip(rms / top, 0, 1) ** 0.7
    level[rms < top * 0.06] = 0   # breath and room noise keep the mouth shut
    return ''.join(str(int(round(v * 9))) for v in level)

def match(script, heard):
    """Whisper words [(word, start, end)] -> [start ms, end ms] per script word, or [] when they do not match."""
    a, b = [norm(w) for w in script], [norm(w) for w, _, _ in heard]
    if not a or not b: return []
    sm = SequenceMatcher(None, a, b, autojunk=False)
    times = [None] * len(a)
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == 'equal' or (tag == 'replace' and i2 - i1 == j2 - j1):
            for k in range(i2 - i1): times[i1 + k] = heard[j1 + k][1:]
        elif tag == 'replace':   # "B612" for "B 612", "twenty-one" for "twenty one": share the span
            s, e = heard[j1][1], heard[j2 - 1][2]
            for k in range(i2 - i1):
                times[i1 + k] = (s + (e - s) * k / (i2 - i1), s + (e - s) * (k + 1) / (i2 - i1))
    hit = sum(t is not None for t in times)
    if hit < len(a) * 0.6: return []
    # words whisper missed: squeeze them between their neighbours
    for i, t in enumerate(times):
        if t is not None: continue
        j = i
        while j < len(times) and times[j] is None: j += 1
        s = times[i - 1][1] if i else (times[j][0] if j < len(times) else 0)
        e = times[j][0] if j < len(times) else s + 0.25 * (j - i)
        for k in range(i, j): times[k] = (s + (e - s) * (k - i) / (j - i), s + (e - s) * (k - i + 1) / (j - i))
    out, last = [], 0
    for s, e in times:
        # whisper gives a word after a pause its last few hundredths only ("or" 3.38-3.42): give it back a start
        if e - s < 0.12: s = min(s, max(last, e - 0.18))
        s = max(s, last); e = max(e, s + 0.05); last = e
        out.append([int(round(s * 100)) * 10, int(round(e * 100)) * 10])
    return out

def load_existing():
    if not os.path.exists(OUT): return {}
    txt = open(OUT, encoding='utf-8').read()
    return json.loads(txt[txt.index('LP_FILM_TIMING =') + 16:].strip().rstrip(';'))

def write(data):
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('/* generated by tools/film-timing.py — for each recording in audio/: mouth = loudness every 50 ms (0-9),\n'
                '   words = [start ms, end ms] of each subtitle word (motion.js WORD), empty if they could not be matched */\n')
        f.write('window.LP_FILM_TIMING = {\n')
        f.write(',\n'.join(json.dumps(k) + ':' + json.dumps(data[k], separators=(',', ':')) for k in sorted(data)))
        f.write('\n};\n')

def main():
    args = sys.argv[1:]
    spec = importlib.util.spec_from_file_location('film_voices', os.path.join(ROOT, 'tools', 'film-voices.py'))
    fv = importlib.util.module_from_spec(spec); spec.loader.exec_module(fv)
    items = [i for i in fv.steps() if os.path.exists(os.path.join(AUDIO, i['key'] + '.mp3'))]
    data = {k: v for k, v in load_existing().items() if k in {i['key'] for i in items}}
    todo = [i for i in items if i['key'] not in data or (not data[i['key']]['words'] and '--retry-words' in args)]
    if '--chapter' in args:
        n = int(args[args.index('--chapter') + 1]); todo = [i for i in todo if i['ch'] == n]
    print(f'{len(items)} recordings, {len(todo)} to time')
    model = None
    if todo and '--mouth-only' not in args:
        from faster_whisper import WhisperModel
        model = WhisperModel(os.environ.get('LP_WHISPER', 'small.en'), device='cpu', compute_type='int8', cpu_threads=os.cpu_count())
    t0, empty = time.time(), 0
    for n, it in enumerate(todo, 1):
        path = os.path.join(AUDIO, it['key'] + '.mp3')
        s = pcm(path)
        entry = {'mouth': mouth(s), 'words': []}
        if model:
            segs, _ = model.transcribe(s, language='en', word_timestamps=True, initial_prompt=it['say'], beam_size=5,
                                       condition_on_previous_text=False, vad_filter=False)
            heard = [(w.word.strip(), w.start, w.end) for seg in segs for w in (seg.words or [])]
            entry['words'] = match(words(it['say']), heard)
            if not entry['words']: empty += 1
        data[it['key']] = entry
        if n % 50 == 0:
            write(data)
            print(f'  {n}/{len(todo)} ({time.time() - t0:.0f}s, {empty} without words)', flush=True)
    write(data)
    print(f'timed {len(todo)} in {time.time() - t0:.0f}s; {len(data)} entries, {sum(1 for v in data.values() if not v["words"])} without word times')

if __name__ == '__main__':
    main()
